# Generated by Django 3.2 on 2020-10-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('Platform', models.CharField(blank=True, choices=[('iosxr', 'CISCO IOSXR'), ('iosxe', 'CISCO IOSXE'), ('ios', 'CISCO IOS')], max_length=30)),
            ],
        ),
    ]
