# Generated by Django 3.2 on 2020-10-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mclag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='port',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
